@startuml
!include ../../puml/eventstorming/eventstorming.puml
allowmixing

Command("CalculateProductCurrentPrice")[
    计算产品当前价格
    --
]

Aggregate("MarketAggregate")[
   市场聚合
   --
   itemId
   productId
]

Aggregate("ProducingAggregate")[
   生产聚合
   --
   itemId
   productId
]

Aggregate("FormulaAggregate")[
   配方聚合
   --
   itemId
   productId
]


class Order{
    itemId
    price
    tradeType
}
class CurrentPrice{
    buyPrice
    sellPrice
}

MarketAggregate <|-- Order : VO
MarketAggregate <|-- CurrentPrice : VO

DomainEvent("CurrentPriceCalculated")[
    产品当前价格已计算
    ---
]
DomainEvent("ProjectDeleted")[
    成功删除项目
    ---
]
DomainEvent("ProjectModified")[
    成功修改项目
    ---
]
DomainEvent("ProjectEnabled")[
     成功启用项目
     ---
]
DomainEvent("ProjectDisabled")[
     成功禁用项目
     ---
]


CreateProject --> ProjectAggregate : invoked on
DeleteProject --> ProjectAggregate : invoked on
ModifyProject --> ProjectAggregate : invoked on
EnableProject --> ProjectAggregate : invoked on
DisableProject --> ProjectAggregate : invoked on



ProjectAggregate --> ProjectCreated : generates
ProjectAggregate --> ProjectDeleted : generates
ProjectAggregate --> ProjectModified : generates
ProjectAggregate --> ProjectEnabled : generates
ProjectAggregate --> ProjectDisabled : generates
@enduml
