server:
  port: 80

spring:
  task:
    base-thread-pool:
      core-pool-size: 20
      max-pool-size: 40
      queue-capacity: 1000
    game-eve-thread-pool:
      core-pool-size: 10
      max-pool-size: 10
      queue-capacity: 1000
  data:
    mongodb:
      uri: mongodb://fanli:fanlipassw0rd@127.0.0.1:64958/fanli
      host: "127.0.0.1"
      port: 64958
      database: "fanli"
      username: "fanli"
      password: "fanlipassw0rd"
      max-connection-life-time: 0
      min-pool-size: 10
      max-pool-size: 100
      max-connection-wait-time: 10000
      max-connection-idle-time: 60000
      maintenance-frequency: 60000
      maintenance-initial-delay: 0
logging:
  config: file:config/log4j2-dev.xml
