# spring boot 配置
spring:
  main:
    lazy-initialization: true
  devtools:
    restart:
      enabled: true
  profiles:
    # 选择运行环境对应的配置文件
    active: dev
  mvc:
    format:
      # 日期格式化
      date: yyyy-MM-dd
  thymeleaf:
    # 关闭模板引擎缓存
    cache: false
  messages:
    # 国际化配置
    basename: i18n.message
    # 直接使用H5框架
    # mode: HTML
server:
  shutdown: graceful
# 可查看哪些自动配置类生效
debug: false
