@startuml
!include ./puml/eventstorming/eventstorming.puml
allowmixing

Command("CreateProject")[
    创建项目
    --
    1.项目属性合法性校验
]
Command("DeleteProject")[
    删除项目
    --
]
Command("ModifyProject")[
    修改项目
    --
]
Command("EnableProject")[
    项目启用
    --
]
Command("DisableProject")[
    项目禁用
    --
]


Aggregate("ProjectAggregate")[
   项目聚合
   --
   1.创建项目
   2.
]
class Project{
    ProjectId
    ProjectName
    isEnabled
}
class Time{


}

DomainEvent("ProjectCreated")[
    成功创建项目
    ---
]
DomainEvent("ProjectDeleted")[
    成功删除项目
    ---
]
DomainEvent("ProjectModified")[
    成功修改项目
    ---
]
DomainEvent("ProjectEnabled")[
     成功启用项目
     ---
]
DomainEvent("ProjectDisabled")[
     成功禁用项目
     ---
]
CreateProject --> ProjectAggregate : invoked on
DeleteProject --> ProjectAggregate : invoked on
ModifyProject --> ProjectAggregate : invoked on
EnableProject --> ProjectAggregate : invoked on
DisableProject --> ProjectAggregate : invoked on

ProjectAggregate <|-- Project : Entity
Project <|-- Time : VO

ProjectAggregate --> ProjectCreated : generates
ProjectAggregate --> ProjectDeleted : generates
ProjectAggregate --> ProjectModified : generates
ProjectAggregate --> ProjectEnabled : generates
ProjectAggregate --> ProjectDisabled : generates

@enduml
