#------------------------Project-------------------------
endless:
  charset: ${endless-charset} # 字符集
  date-pattern: ${endless-date-pattern} # 日期格式
  date-time-pattern: ${endless-date-time-pattern} # 日期时间格式
  data-center-id: ${endless-data-center-id} # 数据中心 ID
  worker-id: ${endless-worker-id} # 工作节点 ID
  sidecar:
    mesh-mode-enabled: ${endless-sidecar-mesh-mode-enabled} # 是否启用 Service Mesh 模式
    host: ${endless-sidecar-host} # 边车主机地址
    port: ${endless-sidecar-port} # 边车端口
#------------------------Server-------------------------
server:
  port: ${server-port} # 服务端口
  undertow:
    worker-threads: ${undertow-worker-threads} # 最大工作线程数
    io-threads: ${undertow-io-threads}# IO 线程数
    server-options:
      idle-timeout: ${undertow-server-options-idle-timeout} # 连接超时时间（毫秒）
      so-backlog: ${undertow-server-options-so-backlog} # 请求队列长度
    max-http-header-size: ${undertow-max-http-header-size} # 最大请求头大小
    buffer-cache-size: ${undertow-buffer-cache-size} # Servlet缓冲区大小
    encoding: ${endless-charset} # URI 编码
  servlet:
    context-path: /  # 默认 context
  error:
    whitelabel:
      enabled: false # 禁用默认错误页面
#------------------------Spring-------------------------
spring:
  application:
    name: tianyan-metadata
  main:
    web-application-type: servlet # 项目类型为 servlet
  profiles:
    active: dev
  output:
    ansi:
      enabled: ${spring-output-ansi-enabled} # 输出 ANSI 编码的控制台颜色
  mvc:
    throw-exception-if-no-handler-found: true # 未找到请求处理器时，抛出异常
  web:
    resources:
      add-mappings: false # 禁用默认静态资源映射
  http:
    multipart:
      max-file-size: ${http-multipart-max-file-size} # 限制单个文件的最大上传大小
      max-request-size: ${http-multipart-max-request-size} # 限制整个请求的最大上传大小
  servlet:
    multipart:
      enabled: ${servlet-multipart-enabled} # 启用文件上传功能
      resolve-lazily: ${servlet-multipart-resolve-lazily} # 延迟解析 multipart 请求，减少内存占用
      max-file-size: ${servlet-multipart-max-file-size} # 限制单个文件的最大上传大小
      max-request-size: ${servlet-multipart-max-request-size} # 限制整个请求的最大上传大小
  cache:
    type: redis
  data:
    redis:
      host: ${redis-host} # Redis 服务器的主机名或 IP 地址
      port: ${redis-port} # Redis 服务器的端口，默认一般是 6379
      database: ${redis-database} # 使用的 Redis 数据库索引，默认通常是 0
      password: ${redis-password} # Redis 服务器的密码，如果启用了认证则需要
      timeout: ${redis-timeout} # 连接超时时间，单位为毫秒（10秒）
      ssl:
        enabled: ${redis-ssl-enabled} # 是否启用 SSL 加密连接，如果 Redis 服务器启用了 SSL 则设置为 true
      lettuce:
        pool:
          min-idle: ${redis-lettuce-pool-min-idle} # 连接池中最小空闲连接数
          max-idle: ${redis-lettuce-pool-max-idle} # 连接池中最大空闲连接数
          max-active: ${redis-lettuce-pool-max-active} # 连接池中最大活动连接数（并发连接数）
          max-wait: ${redis-lettuce-pool-max-wait} # 从连接池获取连接的最大等待时间，-1 表示没有限制
  datasource:
    driver-class-name: ${datasource-driver-class-name}  # 设置数据库驱动类
    url: ${datasource-url} # 数据库连接 URL
    username: ${datasource-username} # 数据库用户名
    password: ${datasource-password} # 数据库密码
    hikari:
      minimum-idle: ${hikari-minimum-idle} # 最小空闲连接数
      maximum-pool-size: ${hikari-maximum-pool-size} # 最大连接池大小
      idle-timeout: ${hikari-idle-timeout} # 空闲连接超时时间（秒）
      max-lifetime: ${hikari-max-lifetime} # 连接最大存活时间（秒）
      connection-timeout: ${hikari-connection-timeout} # 连接超时时间（秒）
      pool-name: ${hikari-pool-name} # 连接池名称
#------------------------Logging------------------------
logging:
  config: ${logging-config}
#-------------------------Minio-------------------------
minio:
  endpoint: ${minio-endpoint} # MinIO 服务的访问地址，包含主机名/IP和端口号
  accessKey: ${minio-accessKey} # MinIO 服务的访问密钥 ID，用于身份验证
  secretKey: ${minio-secretKey} # MinIO 服务的访问密钥（从配置中读取），用于身份验证
  bucket: ${minio-bucket} # 默认存储桶名称（从配置中读取），用于存储数据
  # OkHttp连接池配置，用于控制与 MinIO 服务的连接管理
  connect-pool:
    max-idle: ${minio-connect-pool-max-idle} # 最大空闲连接数，设置较大值可以减少频繁连接创建和关闭
    keep-alive: ${minio-connect-pool-keep-alive} # 空闲连接保活时间，单位为分钟，超过该时间未使用的连接将被关闭
    timeout: ${minio-connect-pool-timeout} # 连接超时时间，单位为秒，超过该时间未能建立连接则会超时
io:
  netty:
    noUnsafe: true # 禁用 Netty 的 Unsafe 代码，提升性能
    noPreferDirect: true # 禁用 Netty 的直接缓冲区，提升性能
#-----------------------Actuator------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    base-path: /actuator # 健康检查根路径
#-------------------------Mybatis------------------------
mybatis-plus:
  type-aliases-package: org.endless.**.mapper
#------------------------Springdoc-----------------------
springdoc:
  api-docs:
    path: ${springdoc-path}/v3/api-docs # 自定义生成的 API 文档路径，默认为 /v3/api-docs
    version: OPENAPI_3_1 # 设置 OpenAPI 版本为 3.1
    groups:
      enabled: true # 启用 API 文档分组功能
  group-configs:
    - group: ${springdoc-group-id1} # 自定义 API 文档分组名称
      display-name: ${springdoc-group-name1} # 自定义 API 文档分组显示名称
      packages-to-scan: ${springdoc-group-package1} # 自定义 API 文档扫描的包路径
  writer-with-default-pretty-printer: true  # 使用默认的响应体格式化工具 PrettyPrinter
  default-produces-media-type: MediaType.APPLICATION_JSON  # 设置默认的响应体类型为 JSON
  show-login-endpoint: true # 显示 SpringBankCardDrivenAdapter Security 登录入口
  default-support-form-data: true # 设置默认支持表单数据
  swagger-ui:
    enabled: true # 启用 Swagger UI 页面
    path: ${endless.springdoc-path}/swagger-ui # 设置 Swagger UI 的访问路径
    url: ${endless.springdoc-path}/v3/api-docs # 设置 Swagger UI 加载 OpenAPI 文档的路径
    config-url: ${endless.springdoc-path}/v3/api-docs/swagger-config # 设置 Swagger UI 的配置路径
    display-request-duration: true # 在 Swagger UI 上显示请求的持续时间（性能分析）
    deep-linking: true # 启用深层链接，允许用户直接跳转到 API 定义的位置
    doc-expansion: none # 控制 API 文档显示时，是否默认展开所有 API 操作，选择项包括：none、list、full
    syntax-highlight:
      theme: obsidian # 选择响应体的语法高亮主题
    urls: # 自定义 Swagger UI 页面的 API 列表
      - name: ${springdoc-group-name1}
        url: ${endless.springdoc-path}/v3/api-docs/${springdoc-group-id1}
